---
title: "LRT"
output: html_document
---

```{r, include=FALSE}
library(dplyr)
library(stringr)
library(coxphf)
library(survival)

# Cleansed cancer data

cancer <- suppressWarnings(tryCatch({
  read.csv("C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Registro Central de Cancer/Data/cancer_cleansed.csv")
}, error = function(e) {
  read.csv("~/Downloads/Registro Central de Cancer/cancer_cleansed.csv")
}, error = function(e) {
  read.csv("C:/Users/lcastro/OneDrive - Centro Comprensivo de Cancer UPR/projects_shared/BBC/Project_Dra. Carola/Data/Registro Central de Cáncer/cancer_cleansed.csv")
}))
cancer <- cancer %>%
  mutate(FollowUpStart = as.Date(FollowUpStart),
         DiagnosisDate = as.Date(DiagnosisDate),
         FollowUpEnd = as.Date(FollowUpEnd),
         maritallabel = str_to_title(ifelse(maritallabel == "unknown",
                                            NA,
                                            maritallabel)),
         Comorb.cat = factor(ifelse(Comorb == '0' , 'No', 
                                    ifelse(as.numeric(Comorb) >= 1, 'Yes', 'Unknown')),
                             levels= c('Yes','No','Unknown')),
         Procedure = factor(Procedure,
                            levels = c("Surgery Only", "Chemotherapy Only",
                                       "Radiotherapy Only", "Chemotherapy and Radiotherapy",
                                       "Other")),
         Comorbidity = case_when(
           Comorb == -1 ~ NA_character_,
           Comorb == 0 ~ "0",
           Comorb == 1 ~ "1",
           Comorb == 2 ~ "2",
           Comorb >= 3 ~ "3+"
         ),
         StageAtDx = factor(StageAtDx,
                            levels = c("Localized", "Regional", "Distant", "Unstaged"),
                            labels = c("Localized", "Regional", "Distant", "Unknown/unstaged")))

cancer_observed <- cancer %>%
  filter(FollowUpYears > 0)
```

```{r}

cancer_observed <- cancer_observed %>%
  mutate(status = ifelse(Vital == 'CVD death',1, 0),
         lagTime = as.numeric(difftime(FollowUpEnd, DiagnosisDate, units = "days")) / 365.25,
         AgeDxCatRecode = case_when(
           AgeDx < 60 ~ "<70",
           AgeDx >= 60 ~ "70+"),
         lagTimeCat2 = case_when(
           lagTime < 3 ~ "1-2",
           lagTime >= 3 ~ "3+",
           TRUE ~ NA_character_))

```

Interacción de lag time con edad
```{r}

# Modelo de Cox
# Modelo reducido
reduced_model_coxph <- coxph(Surv(FollowUpYears, status) ~ lagTimeCat2 + AgeDxCatRecode, data = cancer_observed); reduced_model_coxph

# Modelo con interaccion
full_model_coxph <- coxph(Surv(FollowUpYears, status) ~ lagTimeCat2 * AgeDxCatRecode, data = cancer_observed); full_model_coxph

# Likelihood Ratio Test (LRT)
anova(reduced_model_coxph, full_model_coxph, test = "LRT")

# Modelo de Cox - Firth's penalized maximum likelihood bias reduction method
# Modelo reducido
reduced_model_firth <- coxphf(Surv(FollowUpYears, status) ~ lagTimeCat2 + AgeDxCatRecode, data = cancer_observed); reduced_model_firth

# Modelo con interaccion
full_model_firth <- coxphf(Surv(FollowUpYears, status) ~ lagTimeCat2 * AgeDxCatRecode, data = cancer_observed,
                           maxstep = 0.5, maxit = 500); full_model_firth

# Likelihood Ratio Test (LRT)
anova(reduced_model_firth, full_model_firth, test = "LRT")

```


Interacción de lag time con etapa
```{r}

cancer_observed_clean <- droplevels(subset(cancer_observed, StageAtDx != "Unknown/unstaged"))
# Modelo de Cox
# Modelo reducido
reduced_model_coxph <- coxph(Surv(FollowUpYears, status) ~ lagTimeCat2 + StageAtDx, data = cancer_observed_clean); reduced_model_coxph

# Modelo con interaccion
full_model_coxph <- coxph(Surv(FollowUpYears, status) ~ lagTimeCat2 * StageAtDx, data = cancer_observed_clean); full_model_coxph

# Likelihood Ratio Test (LRT)
anova(reduced_model_coxph, full_model_coxph, test = "LRT")

# Modelo de Cox - Firth's penalized maximum likelihood bias reduction method
# Modelo reducido
reduced_model_firth <- coxphf(Surv(FollowUpYears, status) ~ lagTimeCat2 + StageAtDx, data = cancer_observed_clean); reduced_model_firth

# Modelo con interaccion
full_model_firth <- coxphf(Surv(FollowUpYears, status) ~ lagTimeCat2 * StageAtDx, data = cancer_observed_clean, 
                           maxstep = 0.5, maxit = 500); full_model_firth

# Likelihood Ratio Test (LRT)
anova(reduced_model_firth, full_model_firth, test = "LRT")

```