---
title: "SMRs CVD+BC Statistical Analysis"
author: "Génesis Rodríguez"
date: "`r format(Sys.time(), '%b %d, %Y - %I:%M %p')`"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r libraries, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(readxl)
library(dplyr)
library(mgcv)
library(ggplot2)
library(openxlsx)
library(popEpi)
library(Epi)
library(data.table)  
library(lubridate)
library(stringr)
library(tidyr)
library(gtsummary)
library(gt)
library(webshot)

```

```{r functions}

# To suppress values under 10 for wide data frames

suppress_values <- function(data) {
  data %>%
    mutate(
      Observed = ifelse(as.numeric(Observed) < 10, "<10", sprintf("%.0f", as.numeric(Observed))),
      Expected = ifelse(Observed == "<10", "-", sprintf("%.2f", as.numeric(Expected))),
      SMR = ifelse(Observed == "<10", "-", sprintf("%.2f", as.numeric(SMR))),
      CI.Lower = ifelse(Observed == "<10", "-", sprintf("%.2f", as.numeric(CI.Lower))),
      CI.Upper = ifelse(Observed == "<10", "-", sprintf("%.2f", as.numeric(CI.Upper)))
    )
}

name_columns <- function(df) {
    race_ethnicity_pattern <- "_(White|Black|Asian American, Native Hawaiian and other Pacific Islanders|US Hispanic|PR Hispanic)"
    setNames(
        str_remove(colnames(df), race_ethnicity_pattern),
        colnames(df)
    )
}

create_gt_table <- function(df, groupname_col = NULL) {
  if (!is.null(groupname_col)) {
    table <- df |> 
      gt(groupname_col = groupname_col)
  } else {
    table <- df |> 
      gt()
  }
  
  table <- table |> 
    spanners_and_header() |> 
    cols_label(.list = desired_colnames) |> 
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_row_groups()) |> 
    cols_align(align = "center", columns = everything()) |> 
    tab_source_note(
      source_note = "Note. SMRs were calculated as the observed
number of cardiovascular disease deaths among breast cancer patients divided by the expected number of cardiovascular disease deaths in the race- and ethnic-matched general female U.S. population. Results with <10 events were suppressed."
    )
  
  return(table)
}


# Creating column names

spanners_and_header <- function(gt_tbl) {
  gt_tbl |> 
    tab_spanner(label = md('**White**'), columns = contains('White')) |> 
    tab_spanner(label = md('**Black**'), columns = contains('Black')) |> 
    tab_spanner(label = md('**Asian American, Native Hawaiian<br>and other Pacific Islanders**'), columns = contains('Asian American, Native Hawaiian and other Pacific Islanders')) |> 
    tab_spanner(label = md('**US Hispanic**'), columns = contains('US Hispanic')) |> 
    tab_spanner(label = md('**PR Hispanic**'), columns = contains('PR Hispanic'))
}
```

```{r cancer_data}

# Cleansed cancer data

cancer <- suppressWarnings(tryCatch({
  read.csv("C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Registro Central de Cancer/Data/cancer_cleansed.csv")
}, error = function(e) {
  read.csv("~/Downloads/Registro Central de Cancer/cancer_cleansed.csv")
}, error = function(e) {
  read.csv("~/../../projects_shared/BBC/Project_Dra. Carola/Data/Registro Central de Cáncer/cancer_cleansed.csv")
}))
cancer <- cancer %>%
  mutate(FollowUpStart = as.Date(FollowUpStart),
         DiagnosisDate = as.Date(DiagnosisDate),
         FollowUpEnd = as.Date(FollowUpEnd),
         FollowUpEnd = if_else(month(FollowUpEnd) == 1 & day(FollowUpEnd) == 1,
                        FollowUpEnd + days(1),  # If the date is January 1, add one day
                        FollowUpEnd),
         maritallabel = str_to_title(ifelse(maritallabel == "unknown",
                               NA,
                               maritallabel)),
         Comorb.cat = factor(ifelse(Comorb == '0' , 'No', 
                             ifelse(as.numeric(Comorb) >= 1, 'Yes', 'Unknown')),
                             levels= c('Yes','No','Unknown')),
          Procedure = case_when(
      Surgery == "Yes" & Chemotherapy == "No" & Radiotherapy == "No" ~ "Surgery Only",
      Chemotherapy == "No" & Radiotherapy == "Yes" ~ "Radiotherapy Only",
      Chemotherapy == "Yes" & Radiotherapy == "No" ~ "Chemotherapy Only",
      Surgery == "Yes" & Chemotherapy == "Yes" & Radiotherapy == "Yes" ~ "Chemotherapy and Radiotherapy",
      TRUE ~ "Other"
    ))



  
cancer$yearDiagCat <- cut(cancer$ydiag, 
                   breaks = c(2003, 2009, 2014, 2019), 
                   labels = c("2004-2009", "2010-2014", "2015-2019"),
                   right = TRUE)
cancer$g_deathyear <- cut(cancer$yy_dlc, 
                   breaks = c(2004, 2010, 2016, 2021), 
                   labels = c("2005-2010", "2011-2016", "2017-2021"),
                   right = TRUE)

cancer_observed <- cancer %>%
  filter(FollowUpYears > 0)

```

```{r numerator}

# This function splits case-level observations by calendar time (per), age, and follow-up time
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per))

# 5-year age groups
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per))

```

```{r denominator}

us_reference_raw <- suppressWarnings(tryCatch({
  read.delim("C:/Users/Genesis Rodriguez/Downloads/Statistical Analysis/Inputs/us_reference.txt")
}, error = function(e) {
read.delim("~/Downloads/Statistical Analysis/Inputs/us_reference.txt")
  }))

us_reference_clean <- us_reference_raw %>%
  filter(!Year.of.death %in% c("1990-2022"),
          Cause.of.death.recode %in% c(
            "Diseases of Heart", 
            "Cerebrovascular Diseases", 
            "Atherosclerosis", 
            "Aortic Aneurysm and Dissection", 
            "Other Diseases of Arteries, Arterioles, Capillaries"),
         Age.recode.with..1.year.olds != "Unknown") %>%  
  mutate(across(
    c(Age.Adjusted.Rate, Count, Population, Std.Pop), ~ as.numeric(gsub("[^0-9.]", "", .))),
         across(c(2, 5, 6, 7, 8), as.numeric),     
         across(c(1,3, 4), as.factor)) %>%
  filter(Year.of.death %in% 2004:2021)

us_reference <- us_reference_clean %>%
  filter(Sex == "Female") %>%
  mutate(age_group5 = as.numeric(substr(Age.recode.with..1.year.olds, 1, 2)),
    Age_group = case_when(
      str_detect(Age.recode.with..1.year.olds, "^00|^01|^05|^10|^15|^20|^25|^30|^35") ~ 0,
      str_detect(Age.recode.with..1.year.olds, "^40|^45") ~ 40,
      str_detect(Age.recode.with..1.year.olds, "^50|^55") ~ 50,
      str_detect(Age.recode.with..1.year.olds, "^60|^65") ~ 60,
      str_detect(Age.recode.with..1.year.olds, "^70|^75") ~ 70,
      str_detect(Age.recode.with..1.year.olds, "^80|^85") ~ 80,
      TRUE ~ NA
    )
  ) %>%
  group_by(Year.of.death, Age_group) %>%
  summarise(n = sum(Count),
            Population = sum(Population)) %>%
  mutate(gen_cvd_rate = n / Population) %>%
  rename(deathyear = Year.of.death,
         agegroup = Age_group)

```

# Global SMRs

```{r global}

# PR SMR
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per, Procedure = Procedure, StageAtDx))

pr_smr_general <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95) %>%
  as_tibble() %>%
  mutate(race_eth = "PR Hispanic") %>%
  select(-c(pyrs, p_value)) %>%
  rename(Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

us_smr_general <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_general.txt") %>%
select(Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper) %>%
  rename(race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth) %>%
  mutate(SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected))
  
merged_general <- rbind(pr_smr_general, us_smr_general) %>%
  mutate(race_eth = as.factor(race_eth),
         across(c(Expected:CI.Upper), ~ sprintf("%.2f", as.numeric(.))),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders"))) %>%
  arrange(race_eth)

# Supressing values under 10

merged_general <- suppress_values(merged_general)

# Merging US and PR General
merged_general_wider <- merged_general %>%
  mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI")) |> 
  arrange("Age Group")

# Setting column names
desired_colnames <- name_columns(merged_general_wider)

# Creating gt table
gt_general <- create_gt_table(merged_general_wider)

figure <- ggplot(merged_general, aes(y = race_eth, x = as.numeric(SMR))) +
    geom_point(size = 2, color = "blue") +  # Plot SMR points
    geom_errorbar(aes(xmin = as.numeric(CI.Lower), xmax = as.numeric(CI.Upper)), width = 0.2) +  # Add CI bars
    theme_minimal() +
    labs(x = "Standardized Mortality Ratio (SMR)", y = "Race/Ethnicity") +
    theme(axis.text.x = element_text(hjust = 1)) +
    scale_y_discrete(labels = function(x) str_wrap(x, width = 20)); figure  # Wrap y-axis labels at 20 characters


ggsave("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Graphs/general_graph.png", plot = figure, width = 10, height = 8, dpi = 300,  bg = "white")

```

# Year of death

```{r deathyear_table}

# PR SMRs by Death Year
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per))

pr_smr_deathyear <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95, print = "deathyear") %>%
  as_tibble() %>%
  mutate(race_eth = "PR Hispanic") %>%
  select(-c(pyrs, p_value)) %>%
  rename("Year of Death" = deathyear,
         Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

# US SMRs by Death Year
us_smr_deathyear <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_deathyear.txt") %>%
select(c(Year.of.death.recode,
  Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper)) %>%
  filter(!(Year.of.death.recode %in% c("2000-2021", "2000", "2001", "2002", "2003",
                                       "2004", "Alive at last contact")),
                  Race.Ethnicity.CVD != "All races/ethnicities") %>%
  rename("Year of Death" = Year.of.death.recode, 
         race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth) %>%
  mutate(SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected))

# Merging PR and US by Death Year 

merged_deathyear <- rbind(pr_smr_deathyear, us_smr_deathyear) %>%
  mutate(Observed = as.numeric(Observed),
    across(c(race_eth, "Year of Death"), as.factor),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders"))) %>%
  arrange(race_eth)

# Suppressing values under 10

merged_deathyear <- suppress_values(merged_deathyear)

# Widening by Race/Ethnicity

merged_deathyear_wider <- merged_deathyear %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI")) |> 
  arrange("Year of Death")

# Naming columns
desired_colnames <- name_columns(merged_deathyear_wider)

# Creating gt table

gt_deathyear <- create_gt_table(merged_deathyear_wider); gt_deathyear

# Saving table
gtsave(gt_deathyear, "~/Downloads/Statistical Analysis/Outputs/Tables/DeathYear_table.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/DeathYear_table.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/DeathYear_table.png"),
                 vwidth = 2450,
                 vheight = 1300)

```

```{r deathyear_graph}

# Create the ggplot
figure2 <- ggplot(merged_deathyear, aes(x = `Year of Death`, y = as.numeric(SMR), color = race_eth, fill = race_eth, group = race_eth)) +
  geom_line(size = 1) +  # Line for SMR over years
 # geom_ribbon(aes(ymin = as.numeric(CI.Lower), ymax = as.numeric(CI.Upper)), alpha = 0.2, color = NA) +  # Confidence interval ribbons
  theme_minimal() +
  geom_hline(yintercept = 1, linetype = "solid", color = "black", size = 0.5) +  # Horizontal line at SMR = 1
  labs(
    title = "Standardized Mortality Ratios (SMRs) Over Time",
    subtitle = "Including 95% Confidence Intervals by Race/Ethnicity",
    x = "Year of Death",
    y = "SMR (95% CI)",
    color = "Race/Ethnicity",
    fill = "Race/Ethnicity"
  ) +
  scale_y_continuous(limits = c(0, 35)) +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  guides(
    color = guide_legend(nrow = 2),
    fill = guide_legend(nrow = 2)
  ) +
  theme(
    text = element_text(size = 10),
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 10),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "bottom",
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9)); figure2
  

ggsave("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Graphs/grouped_deathyear_graph.png", plot = figure2, width = 10, height = 8, dpi = 300,  bg = "white")



```

# Grouped Year of death

```{r grouped_deathyear_table}

 pr_smr_g_deathyear <- pr_smr_deathyear %>%
  mutate(`Year of Death` = case_when(
    `Year of Death` >= 2005 & `Year of Death` <= 2010 ~ "2005-2010",
    `Year of Death` >= 2011 & `Year of Death` <= 2016 ~ "2011-2016",
    `Year of Death` >= 2017 & `Year of Death` <= 2021 ~ "2017-2021"
  )) %>%
  group_by(race_eth, `Year of Death`) %>%
  summarise(
    Observed = sum(Observed),
    Expected = sum(Expected),
    .groups = "drop"
  ) %>%
  mutate(SMR = Observed / Expected,
         CI.Lower = ifelse(
           Observed == 0, 0, 
           SMR * exp(- 1.96 * sqrt(1 / Observed))
         ),
         CI.Upper =  ifelse(
           Observed == 0, Inf, 
           SMR * exp(1.96 * sqrt(1 / Observed))
         ))

# US SMRs by Death Year
us_smr_g_deathyear <- us_smr_deathyear %>%
  mutate(`Year of Death` = case_when(
    `Year of Death` >= 2005 & `Year of Death` <= 2010 ~ "2005-2010",
    `Year of Death` >= 2011 & `Year of Death` <= 2016 ~ "2011-2016",
    `Year of Death` >= 2017 & `Year of Death` <= 2021 ~ "2017-2021"
  ),
  Observed = as.numeric(Observed),
  Expected = as.numeric(Expected)) %>%
  group_by(race_eth, `Year of Death`) %>%
   summarise(
    Observed = sum(Observed),
    Expected = sum(Expected),
    .groups = "drop") %>%
  mutate(SMR = Observed / Expected,
         CI.Lower = ifelse(
           Observed == 0, 0, 
           SMR * exp(-1.96 * sqrt(1 / Observed))
         ),
         CI.Upper =  ifelse(
           Observed == 0, Inf, 
           SMR * exp(1.96 * sqrt(1 / Observed)))) %>%
  arrange(race_eth, `Year of Death`)

# Merging PR and US by Death Year 

merged_g_deathyear <- rbind(pr_smr_g_deathyear, us_smr_g_deathyear) %>%
  mutate(`Year of Death` = as.factor(`Year of Death`),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic", "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders")),
         across(c(Expected:CI.Upper), ~ sprintf("%.2f", as.numeric(.))))

# Suppressing values under 10

merged_g_deathyear <- suppress_values(merged_g_deathyear)

# Widening by Race/Ethnicity

merged_g_deathyear_wider <- merged_g_deathyear %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI")) |> 
  arrange("Year of Death")

# Naming columns
desired_colnames <- name_columns(merged_g_deathyear_wider)

# Creating gt table

gt_g_deathyear <- create_gt_table(merged_g_deathyear_wider); gt_g_deathyear

# Saving table
gtsave(gt_deathyear, "~/Downloads/Statistical Analysis/Outputs/Tables/Grouped_DeathYear_table.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/Grouped_DeathYear_table.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/Grouped_DeathYear_table.png"),
                 vwidth = 2450,
                 vheight = 1300)

```

```{r grouped_deathyear_graph}

figure1 <- ggplot(merged_g_deathyear, aes(x = `Year of Death`, y = as.numeric(SMR))) +
    geom_point(size = 0.5, position = position_dodge(width = 0.5)) +
    geom_errorbar(
        aes(ymin = as.numeric(CI.Lower), ymax = as.numeric(CI.Upper)),
        width = 0.2, position = position_dodge(width = 0.5)) +
    geom_hline(yintercept = 1, linetype = "solid", color = "red", size = 0.2) +
    facet_wrap(~ race_eth, ncol = 2) +  # Adjust `ncol` to create square facets
    theme_bw() +
    labs(x = "", y = "SMR (95% CI)") +
    theme(
        text = element_text(size = 7), 
        strip.text = element_text(angle = 0, face = "bold", size = 6), 
        strip.background = element_rect(fill = NA, color = NA),
        axis.text.x = element_text(size = 6, angle = 45, hjust = 1),  
        axis.text.y = element_text(size = 6), 
        legend.position = "none",
        panel.spacing = unit(0.5, "lines"),
    ); figure1


ggsave("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Graphs/g_deathyear.png", plot = figure2, width = 10, height = 8, dpi = 300,  bg = "white")



```

# Year of diagnosis

```{r diagnosis_table}

# PR SMRs by Diagnosis Year
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per, ydiag))

pr_smr_diagnosisyear <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95, print = "ydiag") %>%
  as_tibble() %>%
  mutate(race_eth = "PR Hispanic") %>%
  select(-c(pyrs, p_value)) %>%
  rename("Year of Diagnosis" = ydiag,
         Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

# US SMRs by Death Year
us_smr_diagnosisyear <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_diagnosisyear.txt") %>%
select(c(Year.of.diagnosis,
  Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper)) %>%
  filter(!(Year.of.diagnosis %in% c("2000-2021", "2000", "2001", "2002", "2003", "2020", "2021")),
                  Race.Ethnicity.CVD != "All races/ethnicities") %>%
  rename("Year of Diagnosis" = Year.of.diagnosis, 
         race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth) %>%
  mutate(SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected))

# Merging PR and US by Death Year 

merged_diagnosisyear <- rbind(pr_smr_diagnosisyear, us_smr_diagnosisyear) %>%
  mutate(across(c(race_eth, "Year of Diagnosis"), as.factor),
         across(c(Expected:CI.Upper), ~ sprintf("%.2f", as.numeric(.))),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders"))) %>%
  arrange(race_eth)

# Suppressing values under 10

merged_diagnosisyear <- suppress_values(merged_diagnosisyear)

# Widening by Race/Ethnicity

merged_diagnosisyear_wider <- merged_diagnosisyear %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI")) |> 
  arrange("Year of Diagnosis")

# Naming columns
desired_colnames <- name_columns(merged_diagnosisyear_wider)

# Creating gt table

gt_diagnosisyear <- create_gt_table(merged_diagnosisyear_wider); gt_diagnosisyear

# Saving table
gtsave(gt_diagnosisyear, "~/Downloads/Statistical Analysis/Outputs/Tables/DiagnosisYear_table.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/DiagnosisYear_table.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/DiagnosisYear_table.png"),
                 vwidth = 2450,
                 vheight = 700)

```

```{r diagnosisyear_graph}

# Create the ggplot
figure2 <- ggplot(merged_diagnosisyear, aes(x = `Year of Diagnosis`, y = as.numeric(SMR), color = race_eth, fill = race_eth, group = race_eth)) +
  geom_line(size = 1) +  # Line for SMR over years
 # geom_ribbon(aes(ymin = as.numeric(CI.Lower), ymax = as.numeric(CI.Upper)), alpha = 0.2, color = NA) +  # Confidence interval ribbons
  theme_minimal() +
  geom_hline(yintercept = 1, linetype = "solid", color = "black", size = 0.5) +  # Horizontal line at SMR = 1
  labs(
    title = "Standardized Mortality Ratios (SMRs) Over Time",
    subtitle = "Including 95% Confidence Intervals by Race/Ethnicity",
    x = "Year of Diagnosis",
    y = "SMR (95% CI)",
    color = "Race/Ethnicity",
    fill = "Race/Ethnicity"
  ) +
  scale_y_continuous(limits = c(0, 15)) +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  guides(
    color = guide_legend(nrow = 2),
    fill = guide_legend(nrow = 2)
  ) +
  theme(
    text = element_text(size = 10),
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 10),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "bottom",
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9)); figure2
  

ggsave("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Graphs/diagnosisyear_graph.png", plot = figure2, width = 10, height = 8, dpi = 300,  bg = "white")



```

# Age groups


```{r agegroup_table}

# PR SMRs by Age Group
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per))

pr_smr_agegroup <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95, print = "agegroup") %>%
  as_tibble() %>%
  mutate(race_eth = "PR Hispanic",
         agegroup = case_when(
           agegroup == 0 ~ "0-39",
           agegroup == 80 ~ "80+",
           .default =  paste0(agegroup, "-", agegroup+9))) %>%
  select(-c(pyrs, p_value)) %>%
  rename("Age Group" = agegroup,
         Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

# US Age Groups
us_smr_agegroup <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_agegroup.txt") %>%
select(c(Attained.Age,
  Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper)) %>%
  filter(Attained.Age != "Total") %>%
  rename("Age Group" = Attained.Age, 
         race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth) %>%
  mutate(SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected))
  
# Merging PR and US

merged_agegroup <- rbind(pr_smr_agegroup, us_smr_agegroup) %>%
  mutate(across(c(race_eth, "Age Group"), as.factor),
         Observed = as.numeric(Observed),
         across(c(Expected:CI.Upper), ~ sprintf("%.2f", as.numeric(.))),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders"))) %>%
  arrange(race_eth)

# Supressing values under 10

merged_agegroup <- suppress_values(merged_agegroup)

# Merging US and PR by Age Group
merged_agegroup_wider <- merged_agegroup %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI")) |> 
  arrange("Age Group")

# Setting column names
desired_colnames <- name_columns(merged_agegroup_wider)

# Creating gt table
gt_agegroup <- create_gt_table(merged_agegroup_wider); gt_agegroup

# Sys.setenv(CHROMOTE_CHROME = "/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser")

# Saving table

gtsave(gt_agegroup, "~/Downloads/Statistical Analysis/Outputs/Tables/AgeGroup_table.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/AgeGroup_table.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/AgeGroup_table.png"),
                 vwidth = 2000,
                 vheight = 400)

```

```{r agegroup_graph}

# Create the ggplot
figure3 <- ggplot(merged_agegroup[merged_agegroup$`Age Group` != "0-39", ], aes(x = `race_eth`, y = as.numeric(`SMR`), fill = `race_eth`)) +
    geom_bar(stat = "identity") + 
    facet_wrap(~ `Age Group`, scales = "fixed") + 
    labs(
        x = "Age Group",
        y = "Standardized Mortality Ratio (SMR)",
        fill = "Age Group"
    ) +
    theme_minimal() +
    geom_text(aes(label = `SMR`), vjust = -0.5, size = 3) +  # Add SMR value above each bar
    theme(axis.text.x = element_blank(),
        strip.text = element_text(size = 10, face = "bold")) +
            scale_fill_manual(values = c('#4E86A7', '#6B9F88', '#F1C04A', '#F07F47', '#D08690', '#9E7DB4'),
                               labels = function(x) str_wrap(x, width = 25)) +
  scale_y_continuous(
        breaks = scales::pretty_breaks(n = 6), limits = c(0, 20)); figure3
  

ggsave("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Graphs/agegroup_graph.png", plot = figure3, width = 10, height = 8, dpi = 300,  bg = "white")



```

# Stage 

```{r stage_table}

# PR SMRs by Death Year
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per, StageAtDx))

pr_smr_stage <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95, print = "StageAtDx") %>%
  as_tibble() %>%
  filter(StageAtDx != "Unstaged") %>%
  mutate(race_eth = "PR Hispanic") %>%
  select(-c(pyrs, p_value)) %>%
  rename(Stage = StageAtDx,
         Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

# US SMRs by Death Year
us_smr_stage <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_stage.txt") %>%
select(c(Combined.Summary.Stage..2004..,
  Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper)) %>%
  filter(Combined.Summary.Stage..2004.. %in% c("Localized", "Regional", "Distant"),
    Race.Ethnicity.CVD != "All races/ethnicities") %>%
  rename(Stage = Combined.Summary.Stage..2004.., 
         race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth) %>%
  mutate(SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected))

# Merging PR and US by Death Year 

merged_stage <- rbind(pr_smr_stage, us_smr_stage) %>%
  mutate(across(c(race_eth, Stage), as.factor),
         across(c(Expected:CI.Upper), ~ sprintf("%.2f", as.numeric(.))),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders")),
         Stage = factor(Stage,
         levels = c("Localized", "Regional", "Distant"))) %>%
  arrange(race_eth, Stage)

# Suppressing values under 10

merged_stage <- suppress_values(merged_stage)

# Widening by Race/Ethnicity

merged_stage_wider <- merged_stage %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI"))

# Naming columns
desired_colnames <- name_columns(merged_stage_wider)

# Creating gt table

gt_stage <- create_gt_table(merged_stage_wider); gt_stage

# Saving table
gtsave(gt_stage, "~/Downloads/Statistical Analysis/Outputs/Tables/Stage_table.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/Stage_table.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/Stage_table.png"),
                 vwidth = 2450,
                 vheight = 1300)

```

# Procedure

```{r procedure_table}

# PR SMRs by Death Year
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per, Procedure))

pr_smr_procedure <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95, print = "Procedure") %>%
  as_tibble() %>%
  mutate(race_eth = "PR Hispanic") %>%
  select(-c(pyrs, p_value)) %>%
  rename(Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

# US SMRs by Procedure
us_smr_procedure <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_procedure.txt") %>%
select(c(Merged.Procedures,
  Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper)) %>%
  filter(Race.Ethnicity.CVD != "All races/ethnicities") %>%
  rename(Procedure = Merged.Procedures,
         race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth) %>%
  mutate(SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected),
         Procedure = gsub("\\[OTHER\\]", "Other", Procedure, ignore.case = FALSE))

# Merging PR and US by Death Year 

merged_procedure <- rbind(pr_smr_procedure, us_smr_procedure) %>%
  mutate(across(c(race_eth, Procedure), as.factor),
         across(c(Expected:CI.Upper), ~ sprintf("%.2f", as.numeric(.))),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders")),
         Procedure = factor(Procedure,
                               levels = c("Surgery Only", "Chemotherapy Only",
                                          "Radiotherapy Only", "Chemotherapy and Radiotherapy",
                                          "Other"))) %>%
  arrange(race_eth, Procedure)

# Suppressing values under 10

merged_procedure <- suppress_values(merged_procedure)

# Widening by Race/Ethnicity

merged_procedure_wider <- merged_procedure %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI"))

# Naming columns
desired_colnames <- name_columns(merged_procedure_wider)

# Creating gt table

gt_procedure <- create_gt_table(merged_procedure_wider); gt_procedure

# Saving table
gtsave(gt_procedure, "~/Downloads/Statistical Analysis/Outputs/Tables/Procedure_table.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/Procedure_table.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/Procedure_table.png"),
                 vwidth = 2450,
                 vheight = 1300)

```

# Procedure and Stage

```{r supplemental_table_4, results='asis'}

# PR SMRs - Numerator
c <- lexpand(cancer_observed, status = cvdStatus != 0, 
             birth = birth_date,
             entry = FollowUpStart, # Without those that did not meet follow-up
             exit = FollowUpEnd, 
             breaks = list(per = 2004:2022, age = c(0, 40, 50, 60, 70, 80, Inf)),
             aggre = list(agegroup = age, deathyear = per, Procedure = Procedure, StageAtDx))

# PR SMRs by Procedure and Stage

pr_smr_proc_stage <- sir(coh.data = c, coh.obs = 'from0to1', 
                  coh.pyrs = 'pyrs', 
                  ref.data = us_reference, 
                  ref.rate = 'gen_cvd_rate', 
                  adjust = c('deathyear', 'agegroup'), 
                  test.type = "homogeneity",
                  conf.type = "wald",
                  conf.level = 0.95, print = list(Procedure, StageAtDx)) %>%
  as_tibble() %>%
  mutate(race_eth = "PR Hispanic",
         StageAtDx = ifelse(StageAtDx == "Unstaged", "Unknown/unstaged", StageAtDx)) %>%
  select(-c(pyrs, p_value)) %>%
  rename(Stage = StageAtDx,
         Observed = observed,
         Expected = expected,
         SMR = sir,
        CI.Lower = sir.lo,
        CI.Upper = sir.hi) %>%
  relocate(race_eth)

# US SMRs by Procedure and Stage

us_smr_proc_stage <- read.delim("~/Downloads/Statistical Analysis/Inputs/smr_procedure_stage.txt") %>%
  filter(!(Combined.Summary.Stage..2004.. %in% c("In situ", "Blank(s)", "N/A")),
         Race.Ethnicity.CVD != "All races/ethnicities") %>%
select(c(Merged.Procedures, Combined.Summary.Stage..2004.., Race.Ethnicity.CVD, 
         Observed, Expected, O.E, CI.Lower, CI.Upper)) %>%
  rename(Procedure = Merged.Procedures, 
         Stage = Combined.Summary.Stage..2004.., 
         race_eth = Race.Ethnicity.CVD,
         SMR = O.E) %>% 
  relocate(race_eth, Procedure) %>%
  mutate(Procedure = ifelse(Procedure == "[OTHER]", "Other", Procedure),
         SMR = gsub("#", "", SMR),
         Observed = gsub(",", "", Observed),
         Expected = gsub(",", "", Expected))
  
# US and PR Procedure and Stage

merged_proc_stage <- rbind(pr_smr_proc_stage, us_smr_proc_stage) %>%
    mutate(Procedure = factor(Procedure,
                               levels = c("Surgery Only", "Chemotherapy Only",
                                          "Radiotherapy Only", "Chemotherapy and Radiotherapy",
                                          "Other")),
         Stage = factor(Stage, levels = c("Localized", "Regional", "Distant", "Unknown/unstaged")),
         race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
                                                "White", "Black", "Asian American, Native Hawaiian and other Pacific Islanders"))) %>%
  arrange(race_eth)

# Supressing values under 10

merged_proc_stage <- suppress_values(merged_proc_stage)

# Widen table based on Race/Ethnicity

merged_proc_stage_wider <- merged_proc_stage %>%
 mutate("95% CI" = ifelse(Observed != "<10",
         paste0("(", CI.Lower, " - ", CI.Upper, ")"),
         "-")) %>%
  select(-c(CI.Lower, CI.Upper)) %>%
  filter(Stage != "Unknown/unstaged") %>%
  pivot_wider(names_from = c(race_eth), values_from = c(Observed, Expected, SMR, "95% CI")) |> 
  mutate(Procedure = factor(Procedure,
                               levels = c("Surgery Only", "Chemotherapy Only",
                                          "Radiotherapy Only", "Chemotherapy and Radiotherapy",
                                          "Other")),
         Stage = factor(Stage, levels = c("Localized", "Regional", "Distant"))) |>
  arrange(Procedure, Stage)

# Column titles
desired_colnames <- name_columns(merged_proc_stage_wider)

# Creating gt table
gt_table <- create_gt_table(merged_proc_stage_wider, groupname_col = "Procedure"); gt_table

# Printing
gtsave(gt_table, "~/Downloads/Statistical Analysis/Outputs/Tables/Supplementary_Table_4.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/Supplementary_Table_4.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/Supplementary_Table_4.png"),
                 vwidth = 2450,
                 vheight = 700)

```

```{r figure_1}

merged_proc_stage2 <- merged_proc_stage %>%
  filter(Stage != "Unknown/unstaged",
         Observed >= 10) %>%
  mutate(race_eth = case_when(
    race_eth == "Asian American, Native Hawaiian and other Pacific Islanders" ~ "Asian American,\nNative Hawaiian,\nand other Pacific Islanders",
    TRUE ~ race_eth),
    race_eth = factor(race_eth, levels = c("PR Hispanic", "US Hispanic",
               "White", "Black", "Asian American,\nNative Hawaiian,\nand other Pacific Islanders")))

figure1 <- ggplot(merged_proc_stage2, aes(y = Stage, x = as.numeric(SMR))) +
    geom_point(size = 0.5, position = position_dodge(width = 0.5)) +
    geom_errorbar(
        aes(xmin = as.numeric(CI.Lower), xmax = as.numeric(CI.Upper)),
        width = 0.2, position = position_dodge(width = 0.5)
    ) +
    geom_vline(xintercept = 1, linetype = "solid", color = "black", size = 0.2) +
    facet_grid(Procedure ~ race_eth, scales = "fixed", space = "fixed", switch = "y") +
    theme_minimal() +
    labs(y = "", x = "SMR (95% CI)") +
    theme(
        text = element_text(size = 7), 
        strip.text.y = element_text(angle = 0, face = "bold", size = 6), 
        strip.text.x = element_text(size = 6), 
        strip.background = element_rect(fill = NA, color = NA),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = 6, angle = 45, hjust = 1),  
        axis.text.y = element_text(size = 6), 
        legend.position = "none",
        panel.spacing.y = unit(0.5, "lines"),
        panel.grid = element_blank()); figure1

ggsave("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Graphs/figure1.png", plot = figure1, width = 10, height = 8, dpi = 300,  bg = "white")

```


# Descriptive table

```{r table1}

table1_general <- merged_general_wider %>%
  mutate(Variable = "General",
         across(starts_with("Observed_"), ~ round(as.numeric(.x), 0))) %>%
  relocate(Variable)

table1_agegroup <- merged_agegroup_wider %>%
  rename(Variable = `Age Group`) %>%
  bind_rows(tibble(Variable = "Age Group"),.) %>%
  relocate(Variable)

 table1_stage <- merged_stage_wider %>%
  rename(Variable = Stage) %>%
  bind_rows(tibble(Variable = "Stage"),.) %>%
  relocate(Variable)
 
 table1_procedure <- merged_procedure_wider %>%
  rename(Variable = Procedure) %>%
  bind_rows(tibble(Variable = "Procedure"),.) %>%
  relocate(Variable)
 
 table1_g_deathyear <- merged_g_deathyear_wider %>%
  rename(Variable = `Year of Death`) %>%
  bind_rows(tibble(Variable = "Year of Death"),.) %>%
  relocate(Variable)

combined_table <- rbind(table1_general, table1_agegroup, table1_stage, table1_procedure, table1_g_deathyear) %>%
    mutate(has_na = apply(., 1, function(row) any(is.na(row))), # Rows to make bold
           across(everything(), ~ ifelse(is.na(.), "", .))) # Make NAs Blank

desired_colnames <- name_columns(combined_table)

gt_table1 <- combined_table %>%
    create_gt_table() %>%
    tab_style(
        style = cell_text(weight = "bold"),
        locations = cells_body(rows = has_na)) %>%
  cols_hide(columns = has_na); gt_table1

# Saving table
gtsave(gt_table1, "~/Downloads/Statistical Analysis/Outputs/Tables/Table_1.html")

webshot::webshot("/Users/genesisrodriguez/Downloads/Statistical Analysis/Outputs/Tables/Table_1.html",
                 path.expand("~/Downloads/Statistical Analysis/Outputs/Tables/Table_1.png"),
                 vwidth = 2450,
                 vheight = 1300)
```
