---
title: "NCHS"
author: "Genesis Rodriguez"
date: "2024-06-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

This data is necessary so we can get the CVD death rates for non BC survivors
in the standard population

```{r libraries, include = FALSE}

# Loading packages

library(readxl)
library(gtsummary)
library(dplyr)
library(purrr)
library(tidyr)
library(stringr)

library(ggmap)
library (ggthemes)
library(sf)
library (tigris)

options(tigris_class = "sf")

```

```{r wrangling_census}

census <- suppressWarnings(tryCatch({
  read.csv("C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Datos censales/Intercensal_female_age_grp_est_2000-2023.csv")
}, error = function(e) {
   read.csv("~/Downloads/NCHS/Intercensal_female_age_grp_est_2000-2023-2.csv")
}))

census <- census %>%
  mutate(Age_Groups = case_when(
    Age_Group %in% c(".18 to 24 years", ".25 to 44 years", ".45 to 49 years", ".50 to 54 years", ".55 to 59 years") ~ "18-59",
    Age_Group %in% c(".60 to 64 years", ".65 to 69 years", ".70 to 74 years", 
                     ".75 to 79 years", "70-79", ".80 to 84 years", ".85 years and over") ~ "60+"
  ),
  Age_Groups2 = case_when(
    Age_Group %in% c(".18 to 24 years", ".25 to 44 years", ".45 to 49 years", ".50 to 54 years", ".55 to 59 years") ~ "18-59",
    Age_Group %in% c(".60 to 64 years", ".65 to 69 years") ~ "60-69",
    Age_Group %in% c(".70 to 74 years", ".75 to 79 years") ~ "70-79",
    Age_Group %in% c(".80 to 84 years", ".85 years and over") ~ "80+"
  )) %>%
  relocate(Age_Groups, Age_Groups2) %>%
  mutate_at(4:27, ~ gsub(",", "", .)) %>%
  mutate_at(4:27, as.numeric) 

census1 <- census %>%
  filter(!is.na(Age_Groups)) %>%
  select(-c(Age_Group, Age_Groups2)) %>%
  group_by(Age_Groups) %>%
  summarise(across(everything(), sum, na.rm = TRUE)) %>%
  pivot_longer(
    cols = -Age_Groups,   # Pivot all columns except 'age_group'
    names_to = "Year",   # The new column for the year names
    values_to = "Population"  # The new column for the values
  ) %>%
  mutate(Year = gsub("X", "", Year)) %>% 
  relocate(Year) %>%
  arrange(Year, Age_Groups)


census2 <- census %>%
  filter(!is.na(Age_Groups2)) %>%
  select(-c(Age_Group, Age_Groups)) %>%
  group_by(Age_Groups2) %>%
  summarise(across(everything(), sum, na.rm = TRUE)) %>%
  pivot_longer(
    cols = -Age_Groups2,   # Pivot all columns except 'age_group'
    names_to = "Year",   # The new column for the year names
    values_to = "Population"  # The new column for the values
  ) %>%
  mutate(Year = gsub("X", "", Year)) %>% 
  relocate(Year) %>%
  arrange(Year, Age_Groups2)

```

```{r nchs_data_wrangling, include = FALSE, cache = TRUE}

# Define the range of years to be processed
years <- 2005:2021

# Define the common file paths using placeholders for the year
paths <- c(
  "C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Defunciones/NCHS/Procesadas/Listas/{year}.xlsx",
  "~/Downloads/NCHS/{year}.xlsx",
  "C:/Users/lcastro/OneDrive - Centro Comprensivo de Cancer UPR/projects_shared/BBC/Project_Dra. Carola/Data/NCHS/{year}.xlsx"
)

# Function to read and process each file
read_and_process_file <- function(year) {
  # Replace {year} with the current year in the paths
  file_paths <- sapply(paths, function(path) gsub("\\{year\\}", year, path))
  
  # Try to read the file from one of the possible paths
  mort <- tryCatch({
    read_excel(file_paths[1])
  }, error = function(e) {
    tryCatch({
      read_excel(file_paths[2])
    }, error = function(e) {
      read_excel(file_paths[3])
    })
  })
  
  mort <- mort[rowSums(is.na(mort)) != ncol(mort),]
  
  # Process the dataframe: rename columns and select variables
  mort_processed <- mort %>%
    rename_all(~ snakecase::to_any_case(., case = "snake")) %>%
    select(
      record_type,
      county_of_occurrence_fips,
      detail_age_unit, 
      detail_age, 
      sex,
      icd_code_10_th_revision,
      `1_st_condition`,
      `2_nd_condition`,
      `3_rd_condition`,
      marital_status,
      current_data_year
    ) %>%
    mutate(
      record_type = as.numeric(record_type),  # Ensure these columns are numeric
      detail_age_unit  = as.numeric(detail_age_unit), 
      detail_age  = as.numeric(detail_age), 
      current_data_year  = as.numeric(current_data_year), 
      county_of_occurrence_fips  = as.numeric(county_of_occurrence_fips), 
      across(
        c(icd_code_10_th_revision, `1_st_condition`, `2_nd_condition`, `3_rd_condition`), 
        ~ sub("^(.{3})(.)", "\\1.\\2", .))) # Insert a period after the third character for any 4-character string

  # Return processed dataframe
  return(mort_processed)
}

# Use purrr::map_dfr to apply the function to each year and bind the rows into a single dataframe
mort <- map_dfr(years, read_and_process_file)

         
```

```{r adding_geo_information, include = FALSE}

# Import file with counties and their coordinates
pr_sf <- counties (state = "PR", cb = TRUE)

# Joining our NCHS mortality data with shape file
geo_mort <- mort %>%
  mutate(county_of_occurrence_fips = ifelse(county_of_occurrence_fips == 999, NA, # If no information for county, make NA
                                            paste0(72, sprintf("%03d", county_of_occurrence_fips)))) %>% # Making FIPS codes identical
    left_join(pr_sf, by = c("county_of_occurrence_fips" = "GEOID")) %>% # Joining files
  filter(!is.na(NAME)) # Removing counties with less than 100k in population due to no geometry

ggplot (data = pr_sf) +
  geom_sf (fill = '#A9A9A9', color = "white" , aes (geometry = geometry, fill=NA)) +
  theme_tufte()

```

```{r filtering_cvd_gen, echo = FALSE}

# CVD deaths excluding breast cancer related deaths
cvd_deaths_gen <- mort %>%
  filter(record_type == 1, # Resident of P.R.
         detail_age_unit == 1, # Age in years
         detail_age >= 18 &
           detail_age != 999, # 18 years +
         sex == "F", # Female
         current_data_year != 2004, # Removing deaths outside follow-up period
         grepl("^I(0|1[1,3]|2|3|4|5[0,1]|6|7[0-8])", `icd_code_10_th_revision`), # CVD fatalities
         !grepl("^C50", `2_nd_condition`)|
           !grepl("^C50", `3_rd_condition`)) %>% # Excluding BC fatalities 
  mutate(AgeDeathCat = as.factor(case_when(detail_age >= 18 & detail_age <= 59 ~ "18-59",
                                           detail_age >= 60 ~ "60+",
                                           TRUE ~ NA)),
         AgeDeathCat2 = as.factor(case_when(detail_age >= 18 & detail_age <= 59 ~ "18-59",
                                            detail_age >= 60 & detail_age <= 69 ~ "60-69",
                                            detail_age >= 70 & detail_age <= 79 ~ "70-79",
                                            detail_age >= 80 ~ "80+",
                                            TRUE ~ NA))) %>%
  select(detail_age, icd_code_10_th_revision, current_data_year, AgeDeathCat, AgeDeathCat2)

```

```{r loading_grouped_cvd_BC, echo = FALSE}

# Reading file grouped by year and age groups 0-59, 60+
cvm_by_year_agegroup1 <- suppressWarnings(tryCatch({
  read.csv("C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Registro Central de Cancer/Data/cvm_by_year_agegroup1.csv", row.names = NULL) %>%
  mutate(Year = as.numeric(Year))
}, error = function(e) {
   read.csv("~/Downloads/Registro Central de Cancer/cvm_by_year_agegroup1.csv", row.names = NULL) %>%
  mutate(Year = as.numeric(Year))
}))

# Reading file grouped by year and age groups 0-59, 60-69, 70-79, 80+
cvm_by_year_agegroup2 <- suppressWarnings(tryCatch({
  read.csv("C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Registro Central de Cancer/Data/cvm_by_year_agegroup2.csv", row.names = NULL) %>%
  mutate(Year = as.numeric(Year))
}, error = function(e) {
   read.csv("~/Downloads/Registro Central de Cancer/cvm_by_year_agegroup2.csv", row.names = NULL) %>%
  mutate(Year = as.numeric(Year))
}))

```

```{r joining_cvd_gen_with_cvd_bc, echo = FALSE}

grouped_cvd_deaths_gen <- cvd_deaths_gen %>% group_by(current_data_year, AgeDeathCat) %>% count(); grouped_cvd_deaths_gen
clean_n_cvd_deaths_gen <- left_join(grouped_cvd_deaths_gen, cvm_by_year_agegroup1[, c("Year", "AgeGroup", "cvd_deaths_BC", "PersonYears")], 
          join_by("current_data_year" == "Year",
                  "AgeDeathCat" == "AgeGroup")) %>%
  replace_na(list(cvd_deaths_BC = 0)) %>%
  mutate(NewN = (n - cvd_deaths_BC),
         current_data_year = as.character(current_data_year)) %>%
  select(-c(n, cvd_deaths_BC)) %>%
  rename(n = NewN); clean_n_cvd_deaths_gen

grouped_cvd_deaths_gen2 <- cvd_deaths_gen %>% group_by(current_data_year, AgeDeathCat2) %>% count(); grouped_cvd_deaths_gen2
clean_n_cvd_deaths_gen2 <- left_join(grouped_cvd_deaths_gen2, cvm_by_year_agegroup2[, c("Year", "AgeGroup2", "cvd_deaths_BC", "PersonYears")], 
          join_by("current_data_year" == "Year",
                  "AgeDeathCat2" == "AgeGroup2")) %>%
    replace_na(list(cvd_deaths_BC = 0)) %>%
mutate(NewN = (n - cvd_deaths_BC),
         current_data_year = as.character(current_data_year)) %>%
  select(-c(n, cvd_deaths_BC)) %>%
  rename(n = NewN); clean_n_cvd_deaths_gen2


```

```{r rates}

cvd_rates_gen1 <- left_join(clean_n_cvd_deaths_gen, census1, by = c("current_data_year" = "Year",
                                                "AgeDeathCat" = "Age_Groups")) %>%
  replace_na(list(PersonYears = 0)) %>%
  mutate(Population2 = (Population - PersonYears)) %>%
  select(-c(Population, PersonYears)) %>%
  rename(Population = Population2) %>%
  group_by(current_data_year) %>%
  mutate(gen_cvd_rate = (n/ Population) * 1000); cvd_rates_gen1



cvd_rates_gen2 <- left_join(clean_n_cvd_deaths_gen2, census2, by = c("current_data_year" = "Year",
                                                "AgeDeathCat2" = "Age_Groups2")) %>%
  replace_na(list(PersonYears = 0)) %>%
  mutate(Population2 = (Population - PersonYears)) %>%
  select(-c(Population, PersonYears)) %>%
  rename(Population = Population2) %>%
  group_by(current_data_year) %>%
  mutate(gen_cvd_rate = (n/ Population) * 1000); cvd_rates_gen2


```

```{r adding_2000_US_standardization}

#US 2000 Population by single ages

stdpop.singleages <- suppressWarnings(
  tryCatch({
    read.table("C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Defunciones/2000 US Std Population/stdpop.singleagesthru84.txt", 
               colClasses = "character", quote="\"", comment.char="")
  }, error = function(e) {
    read.table(file.path(Sys.getenv("HOME"), "Downloads/stdpop.singleagesthru84.txt"), 
               colClasses = "character", quote="\"", comment.char="")
  })
) %>%
  filter(startsWith(V1, "20")) %>%
  mutate(Age = as.numeric(substr(V1, 5, 6)),
         Std_Population = as.numeric(substr(V1, 8, 18))) %>%
  select(-V1) %>%
  mutate(Age_Group = case_when(
    Age >= 0 & Age <= 17 ~ "0-17", 
    Age >= 18 & Age <= 59 ~ "18-59",  
    Age >= 60 & Age <= 69 ~ "60-69",  
    Age >= 70 & Age <= 79 ~ "70-79",  
    Age >= 80 ~ "80+",  
    TRUE ~ NA_character_))

# Grouped into 18-59, 60-69, 70-79, 80+

std_age_groups <- stdpop.singleages %>%
  group_by(Age_Group) %>%
  summarise(Std_Population = sum(Std_Population)) %>%
mutate(weight = Std_Population/ sum(Std_Population))

# Integrating into general pop rates
test <- left_join(cvd_rates_gen2, std_age_groups, by = c("AgeDeathCat2" = "Age_Group")) %>%
  mutate(adj_gen_cvd_rate = gen_cvd_rate * weight)

# Comparison of rate and adjusted rate by year
# test %>%
#   filter(current_data_year == 2015) %>%
#   summarise(total_gen_cvd_rate = sum(n)/ sum(Population) * 1000,
#             adj_gen_cvd_rate = sum(adj_gen_cvd_rate))

# gpt
test %>%
  filter(current_data_year == 2015) %>%
  bind_rows(summarise(., 
                      current_data_year = "Total",
                      gen_cvd_rate = sum(n) / sum(Population) * 1000,
                      adj_gen_cvd_rate = sum(adj_gen_cvd_rate)))

# japanese study: age adjusted death rate
# observed death rate in age group * population of age group in standard pop
# / total population in standard pop
# death rate i * std pop i / total std pop

table <- data.frame(currentpop = c(24819361, 82800702, 54473365, 31750716), 
                    n =          c(7123157, 23681001, 13291501, 3810086), 
                    weight =     c(0.12881, 0.401725, 0.299194, 0.170271)) %>% 
         mutate(percent =       n/currentpop * 100, 
         adjustment_factor =    percent * weight); table

round(sum(table$adjustment_factor), 2)
round(sum(table$n)/ sum(table$currentpop) * 100, 2)
```

```{r exporting_gen_pop_rates, echo = FALSE}

# Exporting general population rates by age groups 0-59 and 60+

tryCatch({
  write.csv(cvd_rates_gen1, "C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Defunciones/cvm_rate_gen_pop1.csv")
}, error = function(e) {
  write.csv(cvd_rates_gen1, "~/Downloads/NCHS/cvm_rate_gen_pop1.csv")
})

# Exporting general population rates by age groups 0-59, 60-69, 70-79, 80+

tryCatch({
  write.csv(cvd_rates_gen2, "C:/Users/Genesis Rodriguez/Box/Sanchez-Diaz Lab/CVD and BC/Defunciones/cvm_rate_gen_pop2.csv")
}, error = function(e) {
  write.csv(cvd_rates_gen2, "~/Downloads/NCHS/cvm_rate_gen_pop2.csv")
})

```

```{r cvd_deaths_no_cancer}

# # CVD deaths excluding all cancer related deaths
# cvd_deaths_no_cancer <- mort %>%
#   filter(record_type == 1, # Resident of P.R.
#          detail_age_unit == 1, # Age in years
#          detail_age >= 18, # 18 years +
#          sex == "F", # Female
#           grepl("^I(0|1[1,3]|2|3|4|5[0,1]|6|7[0-8])", `icd_code_10_th_revision`),
#          !grepl("^C|^D(1|2|3|4)", `2_nd_condition`)|
#          !grepl("^C|^D(1|2|3|4)", `3_rd_condition`)) %>% # Excluding cancer fatalities. Neoplasms: C00-D49
#   select(-c(record_type,
#          detail_age_unit,))
# 
# 
# # Breast cancer related deaths
# bc <-   mort %>%
#   filter(record_type == 1, # Resident of P.R.
#          detail_age_unit == 1, # Age in years
#          detail_age >= 18, # 18 years +
#          sex == "F", # Female
#          grepl("^C50", `icd_code_10_th_revision`)|
#            grepl("^C50", `2_nd_condition`)|
#            grepl("^C50", `3_rd_condition`)) # BC fatalities, 3 first causes
# 


```

```{r stats}

mean(cvd_deaths_gen$detail_age)
median(cvd_deaths_gen$detail_age)

hist(cvd_deaths_gen$detail_age, breaks = 115)
```

```{r quality_control, include = FALSE}
# # Alzheimer test ----------
# # Filtering using ICD 10 variable
# test <- mort %>%
#   filter(grepl("^G(30)", icd_code_10_th_revision))
# #Codes included check
# table(test$icd_code_10_th_revision)
# reportN <- 2627 #NVSR number of deaths
# nrow(test) - reportN # Difference in N between report and my analysis
# nrow(test)/reportN*100
# 
# # Filtering using 1st condition
# test2 <- mort %>%
#   filter(grepl("^G(30)", `icd_code_10_th_revision`))
# #Codes included check
# table(test$icd_code_10_th_revision)
# nrow(test2) - reportN # Difference in N between report and my analysis
# nrow(test2)/reportN*100
# 
# # CVD test -----------
# # Filtering
# test <- mort %>%
#  # filter(grepl("^I(00|0[1-9]|11|13|2[0-9]|3[0-9]|4[0-9]|50|51)", icd_code_10_th_revision))
#   filter(grepl("^I(0|11|13|2|3|4|50|51)", icd_code_10_th_revision))
# 
# #Codes included check
# table(test$icd_code_10_th_revision)
# reportN <- 5565 #NVSR number of deaths
# nrow(test) - reportN # Difference in N between report and my analysis
# nrow(test)/reportN*100
# 
# test2 <- mort %>%
#    filter(grepl("^I(0|11|13|2|3|4|50|51)",, `icd_code_10_th_revision`))
# table(test2$`icd_code_10_th_revision`)
# nrow(test2) - reportN # Difference in N between report and my analysis
# nrow(test2)/reportN*100
```
